[package]
name = "sudoku"
version = "0.1.0"
authors = ["Jesse Hallett <jesse@sitr.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.3.7"
varisat = "^0.2.1"
